# Generated by Django 4.2.2 on 2023-06-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='starting_user_message',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_initiates',
            field=models.BooleanField(default=True, verbose_name='Does the bot initiate the conversation?'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='system_message',
            field=models.TextField(blank=True, null=True, verbose_name='System message (optional)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='actor',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10),
        ),
    ]
