# Generated by Django 4.2.2 on 2023-06-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_conversation_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='max_tokens',
            field=models.IntegerField(default=0, verbose_name='Max tokens per message (0 for unlimited)'),
        ),
    ]
