# Generated by Django 4.2.2 on 2023-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_bot_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
